import 'package:dartz/dartz.dart';
import 'package:injectable/injectable.dart';
import 'package:resq/core/error/failures.dart';
import 'package:resq/features/func/data/datasources/community_remote_datasource.dart';
import 'package:resq/features/func/data/models/message_model.dart';
import 'package:resq/features/func/domain/entities/message.dart';
import 'package:resq/features/func/domain/repositories/community_repository.dart';

@LazySingleton(as: CommunityRepository)
class CommunityRepositoryImpl implements CommunityRepository {
  final CommunityRemoteDataSource remoteDataSource;

  CommunityRepositoryImpl(this.remoteDataSource);

  @override
  Stream<Either<Failure, List<Message>>> streamMessages() {
    return remoteDataSource.streamMessages().map<Either<Failure, List<Message>>>((models) {
      final messages = models.map((model) => model.toDomain()).toList();
      // Reverse to show oldest first (newest at bottom)
      return Right(messages.reversed.toList());
    }).handleError((error) {
      return Left(Failure.network(error.toString()));
    });
  }

  @override
  Future<Either<Failure, Unit>> sendMessage({
    required String userId,
    required String userName,
    required String text,
    String? replyToMessageId,
    String? replyToUserName,
    String? replyToText,
  }) async {
    try {
      final message = MessageModel(
        id: '', // Will be generated by Firestore
        userId: userId,
        userName: userName,
        text: text,
        timestamp: DateTime.now(),
        replyToMessageId: replyToMessageId,
        replyToUserName: replyToUserName,
        replyToText: replyToText,
      );

      await remoteDataSource.sendMessage(message);
      return const Right(unit);
    } catch (e) {
      return Left(Failure.network(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Unit>> deleteMessage(String messageId) async {
    try {
      await remoteDataSource.deleteMessage(messageId);
      return const Right(unit);
    } catch (e) {
      return Left(Failure.network(e.toString()));
    }
  }
}

