import 'package:dartz/dartz.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:injectable/injectable.dart';
import 'package:resq/core/error/failures.dart';
import 'package:resq/features/func/data/datasources/dangerous_zone_remote_datasource.dart';
import 'package:resq/features/func/data/models/dangerous_zone_model.dart';
import 'package:resq/features/func/domain/entities/dangerous_zone.dart';
import 'package:resq/features/func/domain/repositories/dangerous_zone_repository.dart';

@LazySingleton(as: DangerousZoneRepository)
class DangerousZoneRepositoryImpl implements DangerousZoneRepository {
  final DangerousZoneRemoteDataSource remoteDataSource;

  DangerousZoneRepositoryImpl(this.remoteDataSource);

  @override
  Stream<Either<Failure, List<DangerousZone>>> streamZones() {
    return remoteDataSource.streamZones().map<Either<Failure, List<DangerousZone>>>((models) {
      final zones = models.map((model) => model.toDomain()).toList();
      // Filter out expired zones (additional safety check)
      final activeZones = zones.where((zone) => !zone.isExpired).toList();
      return Right(activeZones);
    }).handleError((error) {
      return Left(Failure.network(error.toString()));
    });
  }

  @override
  Future<Either<Failure, Unit>> saveZone({
    required String userId,
    required String userName,
    required String name,
    required ZoneType type,
    List<LatLng>? polygonPoints,
    LatLng? center,
    double? radius,
  }) async {
    try {
      final now = DateTime.now();
      final expiresAt = now.add(const Duration(days: 1));
      
      final zone = DangerousZoneModel(
        id: '', // Will be generated by Firestore
        userId: userId,
        userName: userName,
        name: name,
        type: type,
        polygonPoints: polygonPoints,
        center: center,
        radius: radius,
        createdAt: now,
        expiresAt: expiresAt,
      );

      await remoteDataSource.saveZone(zone);
      return const Right(unit);
    } catch (e) {
      return Left(Failure.network(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Unit>> deleteZone(String zoneId) async {
    try {
      await remoteDataSource.deleteZone(zoneId);
      return const Right(unit);
    } catch (e) {
      return Left(Failure.network(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Unit>> deleteExpiredZones() async {
    try {
      await remoteDataSource.deleteExpiredZones();
      return const Right(unit);
    } catch (e) {
      return Left(Failure.network(e.toString()));
    }
  }
}

