// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_IY74cTnZHBBqaR7ZLADfu3gg9FU0laA',
    appId: '1:538737437948:web:b842d14778b288f8a4bb79',
    messagingSenderId: '538737437948',
    projectId: 'resq-6a0b7',
    authDomain: 'resq-6a0b7.firebaseapp.com',
    storageBucket: 'resq-6a0b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDruQDVSQGiG0RNMB7ouuPixs_kB_GoNfU',
    appId: '1:538737437948:android:382827cce877588fa4bb79',
    messagingSenderId: '538737437948',
    projectId: 'resq-6a0b7',
    storageBucket: 'resq-6a0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncUoU-cXmg4YPK2A5bDuxNq6wXIJA1a8',
    appId: '1:833322773378:ios:9fb719c5d40056f3807d9b',
    messagingSenderId: '833322773378',
    projectId: 'resq-7d547',
    storageBucket: 'resq-7d547.firebasestorage.app',
    iosBundleId: 'com.example.resq',
  );

}